<?php

/**
 * @file
 * Integrates Apache Solr Search with Panels.
 *
 * Authors:
 *   Joakim Stai (ximo) <http://drupal.org/user/88701)
 *   Kevin Bridges (cyberswat) <http://drupal.org/user/27802>
 */

/**
 * Implementation of hook_ctools_plugin_directory().
 */
function apachesolr_panels_ctools_plugin_directory($module, $plugin) {
  if ($module == 'ctools' && !empty($plugin)) {
    return "plugins/$plugin";
  }
}

/**
 * Implementation of hook_forms().
 */
function apachesolr_panels_forms() {
  $forms['apachesolr_panels_search_form']= array(
    'callback' => 'search_form',
  );

  return $forms;
}

/**
 * Implementation of hook_search().
 */
function apachesolr_panels_search($op = 'search', $search = NULL) {
  switch ($op) {
    case 'name':
      return t('Apache Solr Panels');

    case 'search':
      // Store information about the search for use in other panes.
      apachesolr_panels_static_search_cache($search);

      try {
        $results = apachesolr_search_execute($search['keys'], $search['filters'], $search['sort'], $search['path'], $search['page']);
        return $results;
      }
      catch (Exception $e) {
        watchdog('Apache Solr', nl2br(check_plain($e->getMessage())), NULL, WATCHDOG_ERROR);
        apachesolr_failure(t('Solr search'), $search['keys']);
      }
      break;

    default:
      // Let the Apache Solr module handle other $ops.
      return apachesolr_search_search($op);
  }
}

/**
 * Store or fetch information about the executed search.
 *
 * This is used by panes other than the results pane to act on the search.
 */
function apachesolr_panels_static_search_cache($search = NULL) {
  static $_search = NULL;

  if (!empty($search)) {
    $_search = array('keys' => '', 'filters' => '', 'sort' => '', 'path' => '', 'page' => 0);
    $_search = array_merge($_search, $search);
  }

  return $_search;
}
